Relocate aalto-xml and stax2-api dependencies in embeddable compiler
Two additional dependencies were added during 213 platform migration:
com.fasterxml:aalto-xml
org.codehaus.woodstox:stax2-api

Packages were not relocated and now might cause failures such as

```
Caused by: java.lang.NoSuchMethodError: 'void com.fasterxml.aalto.in.ReaderConfig.setXMLResolver(javax.xml.stream.XMLResolver)'
```

if proguard classes of kotlin-compiler-embeddable are registered early
in the classpath.